version: '3.9'



services:
  web:
    container_name: skills_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=procollab_skills.settings

#  nginx:
#    container_name: skills_nginx
#    build: ./nginx
#    depends_on:
#      - web
#    ports:
#      - 8000:80


#  db:
#    container_name: skills_db
#    image: postgres
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - 5432:5432
#    restart: always
#    volumes:
#      - skills_postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: skills_redis
    image: redis:latest
    expose:
      - 6379
    volumes:
      - skills_redis_data:/data

volumes:
  skills_postgres_data:
  skills_redis_data:
